micronaut:
    application:
        name: server
---
micronaut:
    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:public"